name: Bug Report
description: Report a bug in Vestige
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `vestige-mcp` with...
        2. Call tool `search` with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      description: Paste any error messages or relevant log output.
      render: shell

  - type: dropdown
    id: install
    attributes:
      label: Installation method
      options:
        - Pre-built binary (GitHub Releases)
        - npm (vestige-mcp)
        - Built from source (cargo build)
    validations:
      required: true

  - type: dropdown
    id: ide
    attributes:
      label: IDE / Client
      options:
        - Claude Code
        - Claude Desktop
        - Cursor
        - VS Code (Copilot)
        - Xcode
        - JetBrains
        - Windsurf
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g. macOS 15.3 (Apple Silicon), Ubuntu 24.04, Windows 11"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Vestige version
      placeholder: "e.g. 2.0.0 (run `vestige --version`)"
    validations:
      required: true
