name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Vestige? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - MCP Tools
        - Cognitive Engine
        - Dashboard / Visualization
        - Search / Retrieval
        - FSRS / Spaced Repetition
        - CLI
        - Documentation
        - Performance
        - Other
    validations:
      required: true
